FIL VM State Tree Update
filecoin-project/specs pull request #1057
Opened 2020-08-13 14:48 UTC by yiannisbot

This PR is an update to the VM state tree and the (most important) functions related to updating it.

@anorth please advise on important things not currently mentioned, as well as on whether the TODO at the end is still relevant or not.

2020-08-13 15:47 UTC, schomatis commented
I'm not sure if we want to make the snapshot system part of the spec, other than that I have little to add here.

2020-08-20 02:28 UTC, anorth approved these changes

2020-08-30 16:08 UTC, hugomrdias requested changes

2020-08-30 16:08 UTC, hugomrdias commented on content/systems/filecoin_vm/state_tree/_index.md
> -{{<embed src="state_tree.id" lang="go" >}}
This file should be deleted

2020-08-31 07:50 UTC, anorth approved these changes

2020-08-31 10:00 UTC, hugomrdias approved these changes

2020-08-31 10:02 UTC, merged