FIL Token Section Update
filecoin-project/specs pull request #1155
Opened 2020-09-11 11:38 UTC by yiannisbot

This PR applies restructuring to the FIL Token section and adds description to some of the subsections. In particular, the FIL Wallet section is temporarily removed and instead we add the Decay Model and the Token Allocation.

The PR will also update the MultiSig Actor and the pointers to the related repositories.

2020-09-15 06:43 UTC, zixuanzh submitted a review, later dismissed
minor suggestions

2020-09-15 06:43 UTC, zixuanzh commented on content/systems/filecoin_token/decay_model.md
> +# Decay Model
Hybrid Minting? Minting Model?

2020-09-15 06:43 UTC, zixuanzh commented on content/systems/filecoin_token/token_allocation.md
> +| `TotalPledgeCollateral` | `StoragePowerActor.`<br>`TotalPledgeCollateral` | Total FIL locked as collateral in all miners. |
Total FIL locked as **pledge** collateral in all miners.

2020-09-17 15:57 UTC, hugomrdias requested changes

2020-09-17 15:57 UTC, hugomrdias commented on content/systems/filecoin_token/multisig.md
> +The Multisig Actor statuses can be found [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_state.go).
We can use symbols lookup to embed this

2020-09-17 16:21 UTC, hugomrdias approved these changes

2020-09-17 16:22 UTC, merged