Chain manager and block producer updates
filecoin-project/specs pull request #1181
Opened 2020-09-26 09:42 UTC by yiannisbot

This PR updates the chain manager and block producer sections, which were mostly in a good state. @schomatis, as discussed, please edit directly to update the text where needed.

Two notes:
- I would probably exclude completely current section 2.4.1.3 "Chain" as I don't see what it adds. @schomatis let me know what you think.
- In section 2.4.1.5.2 on Block Rewards, I have excluded all text and have instead pointed to the correct sections.

@irenegia I would welcome a quick opinion on whether the Election PoSt text in section 2.4.1.5 Block Producer is accurate or needs update.

2020-09-29 11:28 UTC, schomatis submitted a review, later dismissed
I'm not finding much to review here apart from some minor prose edits (I may be missing something though).

> I would probably exclude completely current section 2.4.1.3 "Chain" as I don't see what it adds. @schomatis let me know what you think.

Sure.


> In section 2.4.1.5.2 on Block Rewards, I have excluded all text and have instead pointed to the correct sections.

I can't find that section index.

2020-09-29 13:08 UTC, irenegia commented
@yiannisbot 

> @irenegia I would welcome a quick opinion on whether the Election PoSt text in section 2.4.1.5 Block Producer is accurate or needs update

I can not find any text about Election PoSt in the "Block Producer" section..

2020-09-29 16:02 UTC, irenegia commented
> @irenegia it's this text in line 20:
> 
> "Producing a block for epoch `H` requires computing a tipset for epoch `H-1` (or possibly a prior epoch, if no blocks were received for that epoch). Using the state produced by this tipset, a miner can scratch winning ElectionPoSt ticket(s). Armed with the requisite `ElectionPoStOutput`, as well as a new randomness ticket generated in this epoch, a miner can produce a new block."

I see, this part should be removed. 
Instead we should write something like:

"Producing a block for epoch `H` requires waiting for the beacon entry for that epoch and using it to run GenerateElectionProof. If WinCount ≥ 1 (the miner is elected), the same beacon entry is used to run WinningPoSt. Armed by the ElectionProof ticket (output of GenerateElectionProof) and the WinningPoSt proof, the minere can produce an new block."

2020-09-30 08:34 UTC, irenegia approved these changes

2020-09-30 16:58 UTC, schomatis requested changes
So, after another pass I think we should drop the entire Chain Manager, it doesn't add much value from the spec perspective. At most we can keep the Go API.

2020-09-30 16:58 UTC, schomatis commented on content/systems/filecoin_blockchain/struct/chain_manager/_index.md
> +Once a block has been received and passes syntactic and semantic validation (as explained above) it must be added to the local datastore, regardless of whether it is understood as the best tip at thi
```suggestion

```

This entire line sounds like implementation details. We can rework it if we think it's sound advise and worth staying here but the term *must* should be used with care in a spec I think.

2020-09-30 16:58 UTC, schomatis commented on content/systems/filecoin_blockchain/struct/chain_manager/_index.md
> +Chain selection is a crucial component of how the Filecoin blockchain works. Every chain has an associated weight accounting for the number of blocks mined on it and so the power (storage) they track
Also sounds a little superficial for this section. The advise of staying in consensus is fundamental for any protocol (and if any we should emphasize it there, not here).
```suggestion
```

2020-09-30 20:35 UTC, schomatis commented
I'll leave that up to you. When I started the review I marked those two for delete for sure, and after looking at what was left I didn't see much more remaining so I (confusingly) summed up my review as 'just remove it all', but I'm fine with anything in between those two extremes.

2020-09-30 20:39 UTC, schomatis commented on content/systems/filecoin_blockchain/struct/chain_manager/_index.md
> +Once a block has been received and passes syntactic and semantic validation (as explained above) it must be added to the local datastore, regardless of whether it is understood as the best tip at thi
I'm fine with just changing the word if you think it's useful. It still seems to me too much of an implementation detail, should we really store those tipsets preemptively? Is it really worth the disk space to save some bandwidth? Maybe yes, maybe no, but you see we are already talking about details that don't reflect how the protocol works. They sound to me more of an engineering issue than anything else.

2020-10-01 15:35 UTC, hugomrdias approved these changes

2020-10-01 15:42 UTC, merged